server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gst_db #?options=-c%20TimeZone=UTC
    username: gst_user
    password: mypassword
    schema: public

  flyway:
    enabled: false
    baseline-on-migrate: false
    schemas: public


  jpa:
    properties:
      hibernate:
        default_schema: public

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org:
      postgresql: DEBUG
